### ISSUE TITLE
Enhancement: Allow customers to resize the columns on the Summary page.

### ISSUE THREAD

**Issue by dwg1957** [TheInfiniteKind/moneydance_open#62]
Currently the width of the side bar can be changed by users on the summary page. However there is no control of the other one or two columns.

Giving users the ability to size both of the other columns will also allow them to more effectively utilize the screen space. If truncation is required it should not be of the amount field, but rather the description. In other words any amount field should always contain complete data, if a column is changed so that all data would not be visible it should be the description field that is always truncated.

**Comment by sreilly** [comment]
The two main columns on the summary page can't be made resizable for multiple reasons. However even if possible I wouldn't do it because they adapt to the contents of the panels within them, and default to 50% of the width of the summary page unless they resist compression.

When you refer to an amount column being truncated, can you provide an example screenshot so that I can see if we can fix the layout of that particular panel?
